version: "3"

services:

  nginx:
    image: nginx:latest
    network_mode: host
    volumes:
      - "../config/nginx.conf:/etc/nginx/nginx.conf"

  # redis:
  #   image: redis:latest
  #   network_mode: host
  #   volumes:
  #     - "../config/redis.conf:/usr/local/etc/redis/redis.conf"
